// Package stub provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package stub

// Subject defines model for Subject.
type Subject struct {
	// Name name of the subject
	Name *string `json:"name,omitempty"`
}

// SubjectList defines model for SubjectList.
type SubjectList = []Subject

// Teacher defines model for Teacher.
type Teacher struct {
	// FirstName teacher's first name
	FirstName *string `json:"firstName,omitempty"`

	// LastName teacher's last name
	LastName *string `json:"lastName,omitempty"`
}

// TeachersList defines model for TeachersList.
type TeachersList = []Teacher
